import os

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
S3_ENDPOINT_URL = "http://127.0.0.1:4566/"
S3_PRESIGNED_URL_EXPIRY_TIMEOUT = 3600
S3_DEFAULT_BUCKET_NAME = "bonkers"
S3_DEFAULT_BUCKET_REGION = "ap-south-1"
